server:
  port: ${API_PORT:8080}
elasticsearch:
  hostname: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  index: ${ELASTICSEARCH_AD_INDEX:ad}
analyzer:
  url: ${ANALYZER_URL:http://localhost:5000/analyzer}
