version: '3'
services:
  analyzer:
    image: nemanjam/kp-nlp-analyzer:latest
    container_name: analyzer
    ports:
      - 5000:5000
    networks:
      - api
  api:
    image: nemanjam/kp-nlp-api:latest
    container_name: api
    environment:
      ELASTICSEARCH_HOST: es01
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_AD_INDEX: ad
      ANALYZER_URL: http://analyzer:5000/analyzer
    ports:
    - 8080:8080
    networks:
      - api
      - kp_elastic
  frontend:
    image: nemanjam/kp-nlp-frontend:latest
    container_name: frontend
    environment:
      API_BASE_URL: http://192.168.10.24:8080
    ports:
    - 80:80

networks:
  kp_elastic:
    external: true
  api:
