kafka:
  consumer:
    ad:
      topic: ${KAFKA_AD_TOPIC:ad-topic}
      servers: ${KAFKA_HOST:localhost:9092}
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      consumerGroup: ad-ingestion-1
      pollTimeout: 5000
      maxPollRecords: 100
      fetchMinBytes: 32768
      offsetReset: earliest
elasticsearch:
  hostname: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  index: ${ELASTICSEARCH_AD_INDEX:kp-nlp-ad-search}